config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users do
    resources :posts
  end
  
  resources :posts do
    resources :comments
  end

  get "/followers" => "posts#followers", as: 'my_followers'

  
    root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :post_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

   

    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :username, :phone, :address, :city, :country])
    end

    def after_sign_in_path_for(resource)
      stored_location_for(resource) || "/users/#{resource.id}/posts"
    end
  def after_sign_up_path_for(resource)
      stored_location_for(resource) || "/users/#{resource.id}/posts"
  end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :new_comment, only: [:new, :create]
  before_action :set_comment, only: [:show, :edit, :update]

  def index
    @comments = Comment.all
  end

  def new
    #@comment = @post.comments.build
    @comment = Comment.new
    @posts = Post.all
  end

  def create
    # @comment = @post.comments.build(comment_params)
    @comment = Comment.new(comment_params)
    @comment["post_id"] = @post.id
    @comment["user_id"] = current_user.id
    p @comment.inspect

    if @comment.save
      # redirect_to user_post_path(@post)
      redirect_to post_path(@comment.post_id)
    else   
      # render :new
      redirect_to post_path(@post.id)
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
  end

  private

  def new_comment
    @post = Post.find(params[:post_id])
    # @user = User.find(params[:user_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:text, :user_id, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
    @user = User.find(params[:user_id])
  end

  def edit
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def update
  end

  def destroy
  end

  def create
   @post = Post.new(post_params)
   @user = User.find(params[:user_id])
   @post["user_id"] = @user.id
    if @post.save
      redirect_to user_posts_path
    else
      render :new
    end
  end

  def followers
    # basically, this has nothing to do with any post and it's just here for convenience cos we don't want to
    # write another controller lol

    # @followers = [] # empty array to store

    # loop over current_user.followers
    # for each number in that array,
    # push the User.find(array number) into the above array

    
  end


  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:picture, :post_image, :text, comments_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>
<%= form_for [@post, @comment] do |f| %>
<div class="form-row">
    <%= f.label :text, "Comment" %>
    <%= f.text_field :text %>
</div>
<div class="form-row">
    <%= f.submit "Submit" %>
</div>
<% end %>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script> 
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if notice %>
      <p class="alert alert-success notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>


  <nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <%= link_to image_tag("/instagramlogo.png",width:"100", alt: "logo"),
        '/' %>
  </a>
      <% if user_signed_in? %>
      <div class="container">
            <form class="form-inline mx-auto ">
                <%#= current_user.email %>
                <%#= link_to  "Logout", destroy_user_session_path, method: :delete %> 
                <input class="form-control navbar-center mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                  <a  href="#"><%= link_to image_tag("/homeeicon.png",height:"30", alt: "logo", class: "mt-2"),
        '/' %>
  </a> 
                
  <div class="dropdown-menu" aria-labelledby="navbarDropdown"></div>
  <li class="nav-item dropdown">     
        <a class="nav-link " href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%=image_tag("/profileicon.png",height:"35", alt: "logo")%>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#"><%= current_user.email %></a>
          <a class="dropdown-item" href="#"><%= link_to  "Logout", destroy_user_session_path, method: :delete %></a>
        </div>
      </li>
              </ul> 
            </div>
        <% else %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <form class="form-inline my-2 my-lg-0 ml-auto">
          <button class="btn btn-outline-success my-2 my-sm-0 mr-2"><%= link_to  "Sign up", new_user_registration_path %></button>
          <button class="btn btn-outline-success my-2 my-sm-0"><%= link_to  "Sign In", new_user_session_path %></button>
          </form>
      </div>
      <% end %>
</nav>


<% if user_signed_in? %>
<div class="container">
  <div class="row">
    <div class="col-3">
      <h1>User Profile</h1>

      <div><h1>USER PICTURE TO DO</h1></div>
      <div> <%= current_user.firstname %> <%= current_user.lastname %> </br> <%= current_user.username %> </div>
      <div> 
        <button>FOLLOW</button>
        <button>UNFOLLOW</button> 
      </div>
      <div> Description </div>
      <div> Post Count </div>
      <div> Followers Count </div>


    </div>
    <% end %>
  
    <div class="col-9">
      <%= yield %>
    </div>
  </div>
</div>




    

  
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/followers.html.erb
<h1>Posts#followers</h1>
<p>Find me in app/views/posts/followers.html.erb</p>

<p> loop over @followers etc etc etc </p>

app/views/posts/index.html.erb
<div class="container">
    <%= link_to  "Add Post", new_user_post_path(current_user.id) %>
    <div class="row">
        <div class="col-12">
            <div class="container">
                <div class="row">
                    <% @posts.each do |post| %>
                        <div class="card col-4" style="width: 18rem;">
                            <img class="card-img-top" src="..." alt="Card image cap">
                            <div class="card-body">
                                <div><%= image_tag post.post_image %></div>
                                <div><%= post.text %></div>
                                <div><%= link_to  post.id, user_post_path(current_user.id, post.id) %></div>
                            </div>
                        </div>
                    <%end%>
                 </div>                
            </div>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>
<div class="container">
<%= form_for [@user, @post] do |f| %>
<div class="form-row">
    <%= f.label :picture, "Peekture" %>
    <%= f.text_field :picture, class: "form-control" %>
</div>
<div>
    <%= f.label :post_image %>
    <%= f.file_field :post_image %>
</div>

<div class="form-row">
    <%= f.label :text, "text" %>
    <%= f.text_field :text, class: "form-control" %>
</div>
    


<%= f.submit "Submit", class: "btn btn-primary" %>

<% end %>
</div>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

<%= link_to  "CLICK ME", user_posts_path(current_user.id) %>
<p><%= @post.picture %></p>
<p><%= @post.text %></p>



<%= form_for [@post, @comment] do |f| %>

<%= f.text_field :text %>

<%= f.submit "Submit" %>

<% end %>

 <% @post.comments.each do |comment| %>

    <div class="media text-muted pt-3">
         <img src="" />
          <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark"><%= comment.user.username %> </strong>
            <%= comment.text %>
          </p>
        </div>

<% end %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>